// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrG5cUArrEivxaG-bBgFMR0WnvVTsP95s',
    appId: '1:744655155722:web:a8a910e924b8679c1665f3',
    messagingSenderId: '744655155722',
    projectId: 'dhealth-news-app',
    authDomain: 'dhealth-news-app.firebaseapp.com',
    storageBucket: 'dhealth-news-app.firebasestorage.app',
    measurementId: 'G-W1WHL60MGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjtTuGyabPQon-68bBSdmVkJgoutoZTmg',
    appId: '1:744655155722:android:66ab3666af2b09391665f3',
    messagingSenderId: '744655155722',
    projectId: 'dhealth-news-app',
    storageBucket: 'dhealth-news-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASCzN-YhOl6OCH15xedZxrVIOH5rBs-0g',
    appId: '1:744655155722:ios:b7d7649c88c99a9c1665f3',
    messagingSenderId: '744655155722',
    projectId: 'dhealth-news-app',
    storageBucket: 'dhealth-news-app.firebasestorage.app',
    iosBundleId: 'com.dhealth.news.newsApp',
  );
}
