// Mocks generated by Mockito 5.4.6 from annotations
// in news_app/test/features/main/presentation/get/main_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app/app/data/notification/dto/push_notification_dto.dart'
    as _i6;
import 'package:news_app/app/domain/entities/push_notification.dart' as _i4;
import 'package:news_app/features/notifications/data/repositories/notification_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRxList_0<E> extends _i1.SmartFake implements _i2.RxList<E> {
  _FakeRxList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i3.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RxList<_i4.PushNotification> get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: _FakeRxList_0<_i4.PushNotification>(
              this,
              Invocation.getter(#notifications),
            ),
          )
          as _i2.RxList<_i4.PushNotification>);

  @override
  _i5.Future<void> appendNotification(_i6.PushNotificationDto? pushNotifDto) =>
      (super.noSuchMethod(
            Invocation.method(#appendNotification, [pushNotifDto]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.PushNotificationDto>> getAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotifications, []),
            returnValue: _i5.Future<List<_i6.PushNotificationDto>>.value(
              <_i6.PushNotificationDto>[],
            ),
          )
          as _i5.Future<List<_i6.PushNotificationDto>>);

  @override
  _i5.Future<_i6.PushNotificationDto?> getNotificationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationById, [id]),
            returnValue: _i5.Future<_i6.PushNotificationDto?>.value(),
          )
          as _i5.Future<_i6.PushNotificationDto?>);

  @override
  _i5.Future<int> getUnreadNotificationCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadNotificationCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> markNotificationReadById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationReadById, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markAllNotificationsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllNotificationsRead, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
