// Mocks generated by Mockito 5.4.6 from annotations
// in news_app/test/features/categories/data/repositories/categories_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app/app/data/news/dto/news_response_dto.dart' as _i3;
import 'package:news_app/app/services/network/api_service.dart' as _i2;
import 'package:news_app/features/categories/data/datasources/remote/categories_remote_data_source.dart'
    as _i4;
import 'package:news_app/features/categories/domain/enums/news_category_enum.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNewsResponseDto_1 extends _i1.SmartFake
    implements _i3.NewsResponseDto {
  _FakeNewsResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CategoriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesRemoteDataSource extends _i1.Mock
    implements _i4.CategoriesRemoteDataSource {
  MockCategoriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeApiService_0(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i2.ApiService);

  @override
  _i5.Future<_i3.NewsResponseDto> fetchCategoryNews({
    required _i6.NewsCategoryEnum? category,
    int? pageSize,
    int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategoryNews, [], {
              #category: category,
              #pageSize: pageSize,
              #page: page,
            }),
            returnValue: _i5.Future<_i3.NewsResponseDto>.value(
              _FakeNewsResponseDto_1(
                this,
                Invocation.method(#fetchCategoryNews, [], {
                  #category: category,
                  #pageSize: pageSize,
                  #page: page,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.NewsResponseDto>);
}
