// Mocks generated by Mockito 5.4.6 from annotations
// in news_app/test/features/search/data/datasources/remote/search_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:get/get.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app/app/services/network/api_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiService_2 extends _i1.SmartFake implements _i4.ApiService {
  _FakeApiService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeDio_0(this, Invocation.getter(#client)),
          )
          as _i2.Dio);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void setHeaderToken(String? bearerToken) => super.noSuchMethod(
    Invocation.method(#setHeaderToken, [bearerToken]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i4.ApiService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<_i4.ApiService>.value(
              _FakeApiService_2(this, Invocation.method(#init, [])),
            ),
          )
          as _i5.Future<_i4.ApiService>);

  @override
  _i5.Future<_i2.Response<T>> get<T>({
    String? path = '',
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [], {
              #path: path,
              #queryParameters: queryParameters,
              #options: options,
            }),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(#get, [], {
                  #path: path,
                  #queryParameters: queryParameters,
                  #options: options,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> post<T>({
    String? path = '',
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [], {
              #path: path,
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            }),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(#post, [], {
                  #path: path,
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> put<T>({
    String? path = '',
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [], {
              #path: path,
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            }),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(#put, [], {
                  #path: path,
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> delete<T>({
    String? path = '',
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #path: path,
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            }),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(#delete, [], {
                  #path: path,
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
