// Mocks generated by Mockito 5.4.6 from annotations
// in news_app/test/features/headline/presentation/get/headline_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app/app/domain/entities/news_article.dart' as _i5;
import 'package:news_app/features/headline/data/datasources/remote/headline_remote_data_source.dart'
    as _i2;
import 'package:news_app/features/headline/data/repositories/headline_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHeadlineRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.HeadlineRemoteDataSource {
  _FakeHeadlineRemoteDataSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HeadlineRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeadlineRepository extends _i1.Mock
    implements _i3.HeadlineRepository {
  MockHeadlineRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HeadlineRemoteDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeHeadlineRemoteDataSource_0(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i2.HeadlineRemoteDataSource);

  @override
  _i4.Future<List<_i5.NewsArticle>> fetchTopHeadlines({
    String? country,
    int? pageSize,
    int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopHeadlines, [], {
              #country: country,
              #pageSize: pageSize,
              #page: page,
            }),
            returnValue: _i4.Future<List<_i5.NewsArticle>>.value(
              <_i5.NewsArticle>[],
            ),
          )
          as _i4.Future<List<_i5.NewsArticle>>);
}
