// Mocks generated by Mockito 5.4.6 from annotations
// in news_app/test/features/search/presentation/get/search_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app/app/domain/entities/news_article.dart' as _i5;
import 'package:news_app/features/search/data/datasources/remote/search_remote_data_source.dart'
    as _i2;
import 'package:news_app/features/search/data/repositories/search_repository.dart'
    as _i3;
import 'package:news_app/features/search/domain/enums/search_in_enum.dart'
    as _i6;
import 'package:news_app/features/search/domain/enums/sort_by_enum.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSearchRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.SearchRemoteDataSource {
  _FakeSearchRemoteDataSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i3.SearchRepository {
  MockSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchRemoteDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeSearchRemoteDataSource_0(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i2.SearchRemoteDataSource);

  @override
  _i4.Future<List<_i5.NewsArticle>> searchArticles({
    required String? query,
    _i6.SearchInEnum? searchIn,
    _i7.SortByEnum? sortBy,
    int? pageSize,
    int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchArticles, [], {
              #query: query,
              #searchIn: searchIn,
              #sortBy: sortBy,
              #pageSize: pageSize,
              #page: page,
            }),
            returnValue: _i4.Future<List<_i5.NewsArticle>>.value(
              <_i5.NewsArticle>[],
            ),
          )
          as _i4.Future<List<_i5.NewsArticle>>);
}
